import Head from 'next/head';
import { Wrapper } from './wrapper';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Wrapper>
          <h1>
            <Link href="/repos/list">
              <a>Go Check the posts</a>
            </Link>
          </h1>
        </Wrapper>
      </main>
    </div>
  );
}
